from __future__ import annotations

import os

import pytest

import workers_projects_runtime.service as service_module


RUNTIME_ENV_KEYS = (
    "GLASSHIVE_ENTERPRISE_MODE",
    "GLASSHIVE_SECURITY_MODE",
    "GLASSHIVE_RECURRING_SCHEDULE_OWNER",
    "GLASSHIVE_AUTH_MODE",
    "GLASSHIVE_ENTERPRISE_TENANT_ID",
    "GLASSHIVE_ENABLE_CODEX_PERSONAL_ACCOUNTS",
    "GLASSHIVE_ENABLE_HOSTED_CLAUDE_CONSUMER_AUTH",
    "GLASSHIVE_PROVIDER_SECRET_STORE_ENABLED",
    "GLASSHIVE_PROVIDER_ACCOUNT_HOME_ROOT",
    "GLASSHIVE_PROVIDER_ACCOUNT_ISOLATION",
    "GLASSHIVE_OIDC_PRINCIPAL_CLAIM",
    "GLASSHIVE_OIDC_EMAIL_CLAIM",
    "GLASSHIVE_OIDC_EMAIL_CLAIM_TRUSTED",
    "GLASSHIVE_ALLOWED_EMAIL_DOMAINS",
    "GLASSHIVE_MCP_OAUTH_SUBJECT_CLAIM",
    "GLASSHIVE_MCP_OAUTH_REQUIRED_SCOPES",
    "GLASSHIVE_MCP_OAUTH_TOKEN_SCOPES",
    "GLASSHIVE_MCP_OAUTH_TOKEN_TENANT_ID",
    "GLASSHIVE_ALLOW_PRINCIPAL_ENROLLMENT",
    "GLASSHIVE_ALLOW_EMAIL_REGISTRATION",
    "GLASSHIVE_INTERNAL_ASSERTION_PRIVATE_KEY_FILE",
    "GLASSHIVE_INTERNAL_ASSERTION_JWKS_JSON",
    "GLASSHIVE_INTERNAL_ASSERTION_JWKS_FILE",
    "GLASSHIVE_INTERNAL_ASSERTION_JWKS_URL",
    "GLASSHIVE_AUTH_USER_HEADER",
    "GLASSHIVE_AUTH_EMAIL_HEADER",
    "GLASSHIVE_AUTH_ROLE_HEADER",
    "GLASSHIVE_AUTH_TENANT_HEADER",
    "GLASSHIVE_OWNER_IDENTITY_CLAIMS",
    "GLASSHIVE_OWNER_IDENTITY_ALIASES_JSON",
    "GLASSHIVE_OWNER_IDENTITY_ALIASES_FILE",
    "GLASSHIVE_HOST_WORKERS_ENABLED",
    "GLASSHIVE_HOST_RUNTIME_REQUIREMENTS_JSON",
    "GLASSHIVE_HOST_RUNTIME_REQUIREMENTS_FILE",
    "WPR_HOST_RUNTIME_REQUIREMENTS_JSON",
    "WPR_HOST_RUNTIME_REQUIREMENTS_FILE",
    "GLASSHIVE_HOST_CODEX_NATIVE_MCP_ALLOWLIST",
    "WPR_HOST_CODEX_NATIVE_MCP_ALLOWLIST",
    "GLASSHIVE_HOST_CODEX_PLUGIN_CACHE",
    "WPR_HOST_CODEX_PLUGIN_CACHE",
    "GLASSHIVE_HOST_PLUGIN_DENYLIST",
    "WPR_HOST_PLUGIN_DENYLIST",
    "GLASSHIVE_AUTO_DISCOVER_CODEX_WORKSPACE_DEPS",
    "WPR_AUTO_DISCOVER_CODEX_WORKSPACE_DEPS",
    "GLASSHIVE_CODEX_WORKSPACE_DEPS_ROOT",
    "WPR_CODEX_WORKSPACE_DEPS_ROOT",
    "GLASSHIVE_WORKSPACE_NODE_MODULES",
    "WPR_WORKSPACE_NODE_MODULES",
    "GLASSHIVE_WORKSPACE_NODE_BIN",
    "WPR_WORKSPACE_NODE_BIN",
    "GLASSHIVE_WORKSPACE_PYTHON_BIN",
    "WPR_WORKSPACE_PYTHON_BIN",
    "GLASSHIVE_WORKSPACE_BIN_DIRS",
    "WPR_WORKSPACE_BIN_DIRS",
    "GLASSHIVE_IDLE_TERMINATE_AFTER_S",
    "GLASSHIVE_PAUSED_TERMINATE_AFTER_S",
    "GLASSHIVE_IDLE_REAPER_INTERVAL_S",
    "GLASSHIVE_MAX_RUN_DURATION_S",
    "GLASSHIVE_MAX_WATCH_SESSION_DURATION_S",
    "GLASSHIVE_MAX_ACTIVE_WORKERS_PER_USER",
    "GLASSHIVE_MAX_ACTIVE_WORKERS_PER_TENANT",
    "GLASSHIVE_MAX_WORKSPACES_PER_USER",
    "GLASSHIVE_MAX_WORKSPACES_PER_TENANT",
    "GLASSHIVE_ARTIFACT_DOWNLOAD_MAX_BYTES",
    "GLASSHIVE_ENABLE_ADMIN_API",
    "GLASSHIVE_PROJECT_PROVIDER_ENV",
    "GLASSHIVE_WORKER_SECRET_ENV_EXPOSURE",
    "GLASSHIVE_WORKER_SECRET_ENV_KEYS",
    "GLASSHIVE_SIGNED_LINK_SECRET",
    "GLASSHIVE_LINK_REF_STATE_PATH",
    "GLASSHIVE_LINK_REF_SHARED_GROUP",
    "GLASSHIVE_LINK_REF_TTL_SECONDS",
    "GLASSHIVE_WORKER_ENV_ALLOWLIST",
    "GLASSHIVE_BOOTSTRAP_SOURCE_SECRET",
    "GLASSHIVE_ALLOWED_WORKER_PROFILES",
    "GLASSHIVE_DEFAULT_WORKER_PROFILE",
    "GLASSHIVE_BOOTSTRAP_SOURCE_SECRET",
    "GLASSHIVE_BACKGROUND_CONSUMERS_ENABLED",
    "WPR_API_TOKEN",
    "VIVENTIUM_GLASSHIVE_SERVICE_ASSERTION_SECRET",
    "WPR_DB_PATH",
    "WPR_LINK_REF_TTL_SECONDS",
    "WPR_DEFAULT_EXECUTION_MODE",
    "WPR_HOST_CONVERSATION_SLOTS_PER_CLI",
    "WPR_HOST_MISSION_SLOTS_PER_CLI",
    "WPR_HOST_ACCOUNT_ACTIVE_LIMIT",
    "WPR_HOST_TENANT_ACTIVE_LIMIT",
    "WPR_ENTERPRISE_MODE",
    "WPR_ENTERPRISE_TENANT_ID",
    "WPR_LIBRECHAT_UPLOADS_ROOT",
    "WPR_BOOTSTRAP_SOURCE_ROOTS",
    "WPR_RUNTIME_BACKEND",
    "WPR_ALLOWED_WORKER_PROFILES",
    "WPR_CODEX_CLI_REASONING_EFFORT",
    "WPR_CODEX_CLI_DEFAULT_REASONING_EFFORT",
    "WPR_CODEX_CLI_ALLOWED_REASONING_EFFORTS",
    "WPR_CODEX_CLI_REASONING_EFFORT_FALLBACK",
    "WPR_CODEX_CLI_XHIGH_ROUTE_PROVEN",
    "GLASSHIVE_CODEX_XHIGH_ROUTE_PROVEN",
    "WPR_CODEX_CLI_BASE_URL",
    "WPR_CODEX_CLI_PROVIDER_NAME",
    "WPR_CODEX_CLI_DISABLE_CUSTOM_PROVIDER",
    "WPR_CODEX_CLI_IGNORE_USER_CONFIG",
    "WPR_CODEX_CLI_DISABLE_FEATURES",
    "WPR_CODEX_CLI_PERSONALITY",
    "WPR_CODEX_CLI_CONVERSATION_PROJECT_INSTRUCTIONS",
    "WPR_MODEL_CODEX_CLI",
    "WPR_MODEL_HOST_CODEX_CLI",
    "CODEX_MODEL",
    "GLASSHIVE_HOST_CODEX_INHERIT_PROVIDER_MODEL",
    "WPR_HOST_CODEX_INHERIT_PROVIDER_MODEL",
    "WPR_CODEX_BIN",
    "WPR_CLAUDE_CODE_BIN",
    "WPR_CLAUDE_CODE_ENABLE_CHROME",
    "WPR_CLAUDE_CODE_EFFORT",
    "WPR_OPENCLAW_BIN",
    "VIVENTIUM_ENV_FILE",
    "VIVENTIUM_GLASSHIVE_CALLBACK_URL",
    "VIVENTIUM_GLASSHIVE_CALLBACK_SECRET",
)


os.environ.setdefault("VIVENTIUM_DISABLE_DEFAULT_RUNTIME_ENV", "1")
for key in RUNTIME_ENV_KEYS:
    os.environ.pop(key, None)


@pytest.fixture(autouse=True)
def isolate_runtime_env(monkeypatch: pytest.MonkeyPatch, tmp_path):
    for key in RUNTIME_ENV_KEYS:
        monkeypatch.delenv(key, raising=False)
    monkeypatch.setenv("GLASSHIVE_LINK_REF_STATE_PATH", str(tmp_path / "link_refs.sqlite3"))
    monkeypatch.setenv(
        "GLASSHIVE_BOOTSTRAP_SOURCE_SECRET",
        "synthetic-bootstrap-source-secret",
    )
    # Stubbed runtime tests must not inherit the developer machine's momentary
    # memory or disk pressure. Capacity tests replace this exact projection.
    monkeypatch.setattr(
        service_module,
        "host_resource_usage",
        lambda _leases: service_module.HostResourceUsage(
            child_processes=0,
            threads=0,
            available_memory_bytes=16 * 1024**3,
            available_disk_bytes=64 * 1024**3,
        ),
    )
    yield


@pytest.fixture
def background_consumers_disabled(monkeypatch: pytest.MonkeyPatch) -> None:
    """Keep direct service-unit fixtures isolated from live scheduler threads."""

    monkeypatch.setenv("GLASSHIVE_BACKGROUND_CONSUMERS_ENABLED", "false")
